roles:
    path:     /
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:index" }

roles_show:
    path:     /{id}/show
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:show" }

roles_new:
    path:     /new
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:new" }

roles_create:
    path:     /create
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:create" }
    requirements: { _method: post }

roles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:edit" }

roles_update:
    path:     /{id}/update
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:update" }
    requirements: { _method: post|put }

roles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcuerdosSeguridadBundle:Role:delete" }
    requirements: { _method: post|delete }
