<?php

namespace Acuerdos\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcedenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedenciaRepository extends EntityRepository
{
    public function  countForAdminList($filter) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select($query->expr()->count('t1'))
            ->from('AcuerdosGestionBundle:Procedencia', 't1');

        if ($filter != "") {
            $query->where($query->expr()->like('t1.procedencia', '?1'))
                ->orWhere($query->expr()->like('t1.prefijo', '?1'))
                ->setParameter(1, '%' . $filter . '%');
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    public function findAllForAdminList($column, $order, $filter, $first_result, $max_result) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select('t1')
            ->from('AcuerdosGestionBundle:Procedencia', 't1')
            ->orderBy('t1.' . $column, $order)
            ->setFirstResult($first_result)->setMaxResults($max_result);

        if ($filter != "") {
            $query->where($query->expr()->like('t1.procedencia', '?1'))
                ->orWhere($query->expr()->like('t1.prefijo', '?1'))
                ->setParameter(1, '%' . $filter . '%');
        }

        return $query->getQuery()->getResult();
    }

    public function findCantAcuerdosProcedencia(){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select('t1.id', 't1.procedencia', 't1.prefijo', $query->expr()->count('t1').' as cant')
            ->from('AcuerdosGestionBundle:Procedencia', 't1')
            ->innerJoin('t1.acuerdos','t2')
            ->groupBy('t1.procedencia')
        ;

        return $query->getQuery()->getResult();
    }
}
