<?php

namespace Acuerdos\SeguridadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function  countForAdminList($filter) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select($query->expr()->count('t1'))
            ->from('AcuerdosSeguridadBundle:User', 't1');

        if ($filter != "") {
            $query->where($query->expr()->like('t1.username', '?1'))
                ->setParameter(1, '%' . $filter . '%');
        }

        return $query->getQuery()->getSingleScalarResult();
    }

    public function findAllForAdminList($column, $order, $filter, $first_result, $max_result) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select('t1')
            ->from('AcuerdosSeguridadBundle:User', 't1')
            ->orderBy('t1.' . $column, $order)
            ->setFirstResult($first_result)->setMaxResults($max_result);

        if ($filter != "") {
            $query->where($query->expr()->like('t1.username', '?1'))
                ->orWhere($query->expr()->like('t1.name', '?1'))
                ->orWhere($query->expr()->like('t1.email', '?1'))
                ->setParameter(1, '%' . $filter . '%');
        }

        return $query->getQuery()->getResult();
    }

}
